require("configs.lsp")
-- require("configs.feline")
require("configs.lualine")
require("configs.webdevicons")
require("configs.cmp")
require("configs.telescope")
require("configs.gitsigns")
require("configs.catpuccin")
require("configs.material")
require("configs.autopairs")
require("configs.treesitter-context")
